### ISSUE TITLE
Incorrect behavior when focusing a field without autocomplete

### ISSUE THREAD

**Issue by KidkArolis** [APSL/react-native-keyboard-aware-scroll-view#119] opened 2017-05-07 13:43 UTC
See this gif for a reproducable example: https://github.com/GeekyAnts/NativeBase/issues/534#issuecomment-283331313.

1. Focus a field with keyboard that has autocomplete.
2. Focus a field with keyboard that has no autocomplete - the view scrolls down too much, creating a blank space at the top.

**Comment by Swordsman-Inaction** [comment] 2017-05-10 07:35
Cannot reproduce this with the example below:

```
        <KeyboardAwareScrollView>
          <View style={{height: 350, backgroundColor: 'green'}} />
          <TextInput style={styles.textInput} />
          <TextInput style={styles.textInput} secureTextEntry={true}/>
          <TextInput style={styles.textInput} keyboardType="email-address" />
          <TextInput style={styles.textInput} keyboardType="phone-pad" />
          <TextInput style={styles.textInput} keyboardType="twitter" />
          <TextInput style={styles.textInput} keyboardType="web-search" />
          <TextInput style={styles.textInput} keyboardType="numeric" />
        </KeyboardAwareScrollView>
```

Could you provide a minimum example?

**Comment by alvaromb** [comment] 2017-08-09 10:10
@KidkArolis https://github.com/GeekyAnts/NativeBase/issues/534#issuecomment-321213359

**Comment by alvaromb** [comment] 2017-10-24 09:15
Closing by now. 

Please provide an example isolated from NativeBase to being able to reproduce the issue.

**Closed by alvaromb** 2017-10-24 09:15 UTC
