### ISSUE TITLE
Can't scroll when input is in focus

### ISSUE THREAD

**Issue by zarcode** [APSL/react-native-keyboard-aware-scroll-view#186] opened 2017-10-27 09:06 UTC
I have set `scrollEnabled={true}` so the whole form can scroll while you are filling it up. If I set focus on some TextInput scroll works, but if I type something and then I try scrolling while TextInput is in focus scroll doesn't work. This was working in some older versions of the library.

**Comment by Zhengjian1** [comment] 2017-10-28 06:24
some question

**Comment by johngoren** [comment] 2017-10-30 14:17
I think I have the same question about this life-saving module, but I'm not sure. 

I have a dropdown search bar that presents a scrolling Flatlist of autocompleted results. If I wrap it in the Keyboard-Aware-Scroll-View, I can no longer scroll the results...any ideas?

**Comment by zarcode** [comment] 2017-10-30 18:11
@johngoren my problem gets solved when I rollback to v0.3.0, maybe it will work for you too.

**Comment by HilSny** [comment] 2017-10-31 01:12
I also rolled back to v0.3.0. The issue we had was that the input would not scroll to focus unless we had already focused that input previously. So on initial load, when I would focus next input it only scrolled when I got to the part of the window where it would have to scroll to show the field itself. 

However if I refocused the top input and tried again, it would scroll to each individual input like normal. Version 3.0 scrolls to input on initial load, it doesn't require dirty-ing the textInput first.

Hope this helps explain the problem better.

**Comment by alvaromb** [comment] 2017-10-31 08:56
Hi!

Back to the office, sorry for the delay. Can you set up a minimum example reproducing the issue???

Thanks!

**Comment by kanslervkl** [comment] 2017-10-31 09:52
1) Tap on some input filed (screen was scrolling, and content offset apply - it's ok)
2) tap on another input field 
3) tap on empty space 
4)result - keyboard doesn't hidden

**Comment by Thanmai-C** [comment] 2017-11-01 07:11
When i am using a textinput field which has multiLine prop and the whole thing is surrounded by the KeyboardAwareScrollView , the keyboard overlaps the textfield as the text size increases and cannot see what is typed and focus.

**Comment by zarcode** [comment] 2017-11-01 09:48
Here a code sample:
```
import React, {Component} from 'react';
import { TextInput, Text } from 'react-native';
import PropTypes from 'prop-types';
import { KeyboardAwareScrollView } from 'react-native-keyboard-aware-scroll-view';

class LinkAccount extends Component {
    constructor(props) {
        super(props);
        this.state = { text: '' };
    }

    render() {
        return (
            <KeyboardAwareScrollView
                keyboardShouldPersistTaps="handled"
                resetScrollToCoords={{ x: 0, y: 0 }}
                keyboardOpeningTime={0}
                scrollEnabled={true}
            >
                <Text style={{ marginBottom: 400 }}>
                    Lorem ipsum dolor sit amet.
                </Text>
                <TextInput
                    style={{height: 40, borderColor: 'gray', borderWidth: 1}}
                    onChangeText={(text) => this.setState({text})}
                    value={this.state.text}
                />

            </KeyboardAwareScrollView>
        );
    }
}

LinkAccount.propTypes = {};
LinkAccount.defaultProps = {};

export default LinkAccount;
```
The issue I have is: Can't scroll when there is any content in TextInput (when it's dirty). When its empty, no problem. This was not the case in previous versions of this lib.

Here is a video of issue https://screencast.com/t/Acrsuby6ZewG

**Comment by kidmysoul** [comment] 2017-11-07 03:44
I have the same problem. I Wrapped my contents in KeyboardAwareScrollView.
When I 'm going to type in textinput, the whole thing goes fine (scroll...) but when I typed something , the contents height?? suddenly changed and the scroll doesnot work.

**Comment by malcevicius** [comment] 2017-11-07 19:24
@zarcode I can reproduce this also.

Btw. From @zarcode video, it looks like "KeyboardAwareScrollView" has two different ScrollViews inside depending on the keyboard status. To spot the difference keep your attention on the scroll indicator. When the keyboard is disabled there is no scroll indicator on ScrollView, but when the keyboard is enabled – ScrollView changes to a new one with the scroll indicator.
The problem occurs, when typing something inside textInput changes the second ScrollView to the first one without scroll indicator.
Hopefully, it will help to fix this issue.

**Comment by alvaromb** [comment] 2017-11-08 08:59
I will check this out today, thanks for reporting!

**Comment by alvaromb** [comment] 2017-11-14 08:05
@malcevicius this module doesn't have two `ScrollView`s.

I will check this issue today.

**Comment by henrytndrly** [comment] 2017-11-17 17:10
From what I can gather, `KeyboardAwareHOC` resets the state var `keyboardSpace` during `componentWillReceiveProps`, which gets fired due to potential changes from text input events in the text input fields (and potentially other events), and it is `keyboardSpace` which controls the vertical offset due to a visible keyboard.

I've managed to have a workaround by removing the `componentWillReceiveProps` code from `KeyboardAwareHOC`. I'm not suggesting that as the long term fix, as I'm not sure what the 'keyboard spacer reset' behaviour was meant to do...

**Comment by johngoren** [comment] 2017-12-04 07:25
Hmm, wondering if anyone has had any breakthroughs on a long-term fix for this. Is the problem all down to that keyboardSpace reset?

**Comment by FiW** [comment] 2018-01-11 08:30
any news?

**Comment by LRNZ09** [comment] 2018-01-12 14:31
It happens to me too.

**Closed** 2018-01-12 14:37 UTC

**Comment by alvaromb** [comment] 2018-01-12 14:43
Hello!

Please test the new release and let me know if it solves this issue https://github.com/APSL/react-native-keyboard-aware-scroll-view/releases/tag/v0.4.2

PS: I've been taking some weeks out due to GH "maintainer burnout". Please ping me if somebody wants to be added as collaborator into this repo. Soon it will live under a new APSL project called [InterfaceKit for React Native](https://github.com/InterfaceKit).

**Comment by rochapablo** [comment] 2018-01-17 18:13
I still unable to scroll when the keyboard it's opened (Android).

**Comment by crisshaker** [comment] 2021-06-30 06:08
I still have this issue. Can't scroll on Android when the keyboard is open. Works fine on iOS tho.
