### ISSUE TITLE
scrollToPosition does not work on Android

### ISSUE THREAD

**Issue by rizkyario** [APSL/react-native-keyboard-aware-scroll-view#294] opened 2018-08-15 11:53 UTC
scrollToPosition works fine on iOS but does not work on Android.
I've set `windowSoftInputMode` to `adjustPan`
Any idea how to make it work on android?

```es6
let scroll;
const scrollPosition = 200;
const SignupForm = (props: Props) => (
  <KeyboardAwareScrollView
    contentContainerStyle={styles.container}
    keyboardShouldPersistTaps="always"
    enableOnAndroid
    enableAutomaticScroll={false}
    innerRef={(ref) => { scroll = ref; }}
  >
    <View style={styles.row}>
      <TextField
        title={props.intl.formatMessage({ id: 'SignupForm.field.email' })}
        value={props.signupForm.email}
        onFocus={() => scroll.props.scrollToPosition(0, scrollPosition)}
      />
    </View>
    {/* ....More TextFields here.... */}
    <View style={styles.row}>
      <TextField
        title={props.intl.formatMessage({ id: 'SignupForm.field.password' })}
        value={props.signupForm.password}
        onFocus={() => scroll.props.scrollToPosition(0, scrollPosition)}
      />
    </View>
    <View style={styles.row}>
      <Button
        onPress={props.onSubmitForm}
        label={props.intl.formatMessage({ id: 'SignupForm.createAccount' })}
      />
    </View>
  </KeyboardAwareScrollView>
);
```

**Comment by dreamHeroK** [comment] 2018-08-24 02:52
Do you resolve this problem?I have this problem too.

**Comment by rizkyario** [comment] 2018-08-24 07:44
@dreamHeroK Still having this issue.
Currently using different approach using [keyboardAvoidingView](https://facebook.github.io/react-native/docs/keyboardavoidingview) with keyboardVerticalOffset

**Comment by Moreno97** [comment] 2018-08-24 12:48
Ok guys, you should use this in order to scroll to a certain position:

`this._scroll.scrollToPosition(0, scrollPosition)`

It seems that documentation part is deprecated, we will update it as soon as possible.

**Comment by rizkyario** [comment] 2018-08-25 07:34
@Moreno97 That should be equivalent with the code that I'm using I suppose, `scroll.props.scrollToPosition(0, scrollPosition)` there's no `this` because it's a pure function.

**Comment by Moreno97** [comment] 2018-08-27 09:42
@rizkyario Of course, you should move the function out of scope like:

`_scrollTo = (position) => {
  this.scroll.scrollToPosition(0, position)
}
`
And call it as:
`onFocus={() => this._scrollTo(0, scrollPosition)}`
This way, you reuse code and avoid more errors.

**Comment by Moreno97** [comment] 2018-08-27 09:48
@rizkyario Can you try the follows?

scroll.scrollToPosition(0, scrollPosition)

**Comment by Moreno97** [comment] 2018-08-27 09:58
@rizkyario Can you try the follows?
`scroll.scrollToPosition(0, scrollPosition)`
Without the props.

**Comment by rizkyario** [comment] 2018-08-27 19:42
@Moreno97 It will give me this error 
```
undefined is not a function (evaluating 'scroll.scrollToPosition(0, scrollPosition)')
```

**Comment by Moreno97** [comment] 2018-08-30 12:27
@rizkyario which version are you using?

**Comment by rizkyario** [comment] 2018-08-30 17:31
@Moreno97 `"react-native-keyboard-aware-scroll-view": "^0.6.0",`

**Comment by Moreno97** [comment] 2018-08-30 17:48
The last version is 0.7.2, you should update to the latest, because maybe the API has changed along the versions.

**Comment by rizkyario** [comment] 2018-09-02 06:49
@Moreno97 Still having the same problem.
@dreamHeroK Did you try to do @Moreno97's suggestions?

**Comment by Moreno97** [comment] 2018-09-03 14:56
@rizkyario does not scroll with the last version? We can't reproduce the issue, since it works as expected (we have a React class instead of a pure function, but this should not affect). As I said before, calling `scroll.scrollToPosition()` works without problems.

**Comment by tmwd** [comment] 2018-09-13 15:35
`v"^0.7.2"`, `scrollTo({x: X, y: Y})` does not working for android

**Comment by anjar10** [comment] 2018-10-11 07:48
@tmwd few minutes ago I also facing same issue. I solved it by using `scrollToPosition` method provided by this library.
Don't forget to set `enableOnAndroid` props to true and use `innerRef` method to get valid ref.

**Comment by Moreno97** [comment] 2018-10-15 14:48
Please try @anjar10 solution, forget to mention that you should use `innerRef` and also `scrollToPosition` as before.

**Closed** 2018-10-15 14:49 UTC
Labels: android

**Comment by dreamHeroK** [comment] 2018-10-31 06:49
change MainActivity ``` android:windowSoftInputMode="adjustResize"``` to  ```android:windowSoftInputMode="adjustPan" ``` solve my  problem

**Comment by Tichuottt** [comment] 2019-07-05 03:14
scrollToPosition doesn't work on android. I've applied android:windowSoftInputMode="adjustPan" and enableOnAndroid props to true

**Comment by harrymash2006** [comment] 2019-07-23 20:09
it does not work for me either! using react-native 0.59.8 and react-native-keyboard-aware-scroll-view 0.8.0

**Comment by MaiconGilton** [comment] 2021-08-24 13:49
I fixed that by changing the following function in KeyboardAwareHOC.js:

```
scrollToPosition = (x: number, y: number, animated: boolean = true) => {
      const responder = this.getScrollResponder()
       responder && responder.scrollResponderScrollTo({ x, y, animated })
}
```
to

```
scrollToPosition = (x: number, y: number, animated: boolean = true) => {
     const responder = this.getScrollResponder()
     responder && responder.scrollTo({ x, y, animated })
}
```

scrollResponderScrollTo is deprecated now.
