### ISSUE TITLE
Extra empty space on top of the screen

### ISSUE THREAD

**Issue by shrutic** [APSL/react-native-keyboard-aware-scroll-view#115] opened 2017-04-18 20:34 UTC
I have worked on moving the Header inside the KeyboardAwareScrollView. And I have 3 text fields ( 2 oneline and one multi-line) below it. When I tap on any of these text fields and then tap outside to dismiss keyboard, I get this empty white space on top. 

KeyboardAwareScrollView version: 0.2.8
React native version: 0.43.3
 ```
              <KeyboardAwareScrollView
                    automaticallyAdjustContentInsets={false}
                    keyboardShouldPersistTaps='always'
                    scrollEventThrottle={10}
                    extraHeight={250}
                    resetScrollToCoords={{x: 0, y: 0}}
                    onKeyboardWillShow={this.onKeyboardWillShow.bind(this)}
                    onKeyboardWillHide={this.onKeyboardWillHide.bind(this)}
                >
```

Not sure what I am missing. As per this [thread](https://github.com/APSL/react-native-keyboard-aware-scroll-view/issues/84)  , the latest 0.2.8 should have the fix, but it didnt work for me.

**Comment by Swordsman-Inaction** [comment] 2017-04-19 02:16
@shrutic I tried with the code you provide, but cannot find the issue you said. Could you provide a simple demo to reproduce this issue?

**Comment by dylannlaw** [comment] 2017-04-23 04:45
I am having the same issue. It works okay in Android simulator but not in iOS simulator. 
additional space is added on top of the first text input.

**Comment by Swordsman-Inaction** [comment] 2017-04-25 08:36
@dylannlaw I tested this with the code: 
```
      <View style={{flex: 1, backgroundColor: '#f6f6f6'}}>
        <KeyboardAwareScrollView
           automaticallyAdjustContentInsets={false}
           keyboardShouldPersistTaps='always'
           scrollEventThrottle={10}
           extraHeight={250}
           resetScrollToCoords={{x: 0, y: 0}}
        >
          <View style={{marginTop: 25}}>
            <Text style={{fontSize: 16}}>
              Header
            </Text>
          </View>
          <TextInput style={styles.textInput} />
          <TextInput style={styles.textInput} />
          <TextInput style={styles.textInput} />
          <TextInput style={styles.textInput} />
          <TextInput style={styles.textInput} />
          <TextInput style={styles.textInput} />
          <TextInput style={styles.textInput} />
          <TextInput style={styles.textInput} />
          <TextInput style={styles.textInput} />

        </KeyboardAwareScrollView>
      </View>
```
But I cannot reproduce it. Could you write a simple demo to reproduce it?

**Comment by nguyenhvubk** [comment] 2017-04-25 11:22
I think the issue would be produced if you do not wrap the KeyboadAwareScrollview under FULL screen View.
I also have this issue when i call it below a header view
Just guessing

**Comment by Swordsman-Inaction** [comment] 2017-04-25 11:58
@nguyenhvubk 
Like this ?

```
      <View style={{flex: 1, backgroundColor: '#f6f6f6'}}>
        <View style={{height: 44, backgroundColor: 'blue'}}>
          <Text style={{fontSize: 16, marginTop: 20}}>
            NavigationBar
          </Text>
        </View>
        <KeyboardAwareScrollView
           automaticallyAdjustContentInsets={false}
           keyboardShouldPersistTaps='always'
           scrollEventThrottle={10}
           extraHeight={250}
           resetScrollToCoords={{x: 0, y: 0}}
        >
          <View>
            <Text style={{fontSize: 16}}>
              Header
            </Text>
          </View>
          <TextInput style={styles.textInput} />
          <TextInput style={styles.textInput} />
          <TextInput style={styles.textInput} />
          <TextInput style={styles.textInput} />
          <TextInput style={styles.textInput} />
          <TextInput style={styles.textInput} />
          <TextInput style={styles.textInput} />
          <TextInput style={styles.textInput} />
          <TextInput style={styles.textInput} />

        </KeyboardAwareScrollView>
      </View>
```

Still cannot reproduce. 😕

**Comment by nguyenhvubk** [comment] 2017-04-25 13:23
Update: still get this issue when put KeyboardAwareScrollView outside, will try your code

**Comment by Swordsman-Inaction** [comment] 2017-04-26 02:54
@nguyenhvubk 
glad to help.

@shrutic @dylannlaw 
Do you still get this issue?  I'll close this issue later if you don't have other questions.

**Comment by dylannlaw** [comment] 2017-04-26 05:39
You might proceed with closing this issue as I tried another library which supported Android at the same time.

**Comment by alvaromb** [comment] 2017-04-26 08:18
Hi @dylannlaw!

Can you point us the library you're using? It might help us to solve the issue. Thanks!

**Comment by dylannlaw** [comment] 2017-04-26 08:23
@alvaromb I'm using Native Base component and I wrap all my input component with a container component and it works seamlessly for both iOS and Android.

**Comment by alvaromb** [comment] 2017-04-26 08:43
@dylannlaw Native Base is using `keyboard-aware-scroll-view` https://github.com/GeekyAnts/NativeBase/blob/master/package.json#L43

**Comment by dylannlaw** [comment] 2017-04-26 08:46
@alvaromb ya I am aware of that but it does not have the problem that @shrutic mentioned.

**Comment by shrutic** [comment] 2017-04-26 15:19
I still get this issue. Very busy to come up with demo app

**Comment by Swordsman-Inaction** [comment] 2017-04-27 04:06
I'll close this issue for now. You can always re-open it after providing a reproducible demo.

**Closed by Swordsman-Inaction** 2017-04-27 04:06 UTC

**Comment by MSchmidt** [comment] 2017-06-03 10:45
Had the same issues. What solves it is to add ``automaticallyAdjustContentInsets={false}`` to ``KeyboardAwareScrollView``.

**Comment by Palisand** [comment] 2017-06-08 16:48
Thank you @MSchmidt ! So to confirm, this is only an iOS issue? [`automaticallyAdjustContentInsets`](https://facebook.github.io/react-native/docs/scrollview.html#automaticallyadjustcontentinsets) is an iOS-only prop.

**Comment by JansenZ** [comment] 2017-08-22 08:47
it works! thank u @MSchmidt

**Comment by alvaromb** [comment] 2017-08-22 08:50
This is an upstream issue caused by `ScrollView` component, it's not related to this library.
