### ISSUE TITLE
[KeyboardAwareFlatList] Not working with multiline TextInput

### ISSUE THREAD

**Issue by omar-salah-elboredy** [APSL/react-native-keyboard-aware-scroll-view#227] opened 2018-02-15 17:18 UTC
When multiline prop is set in the TextInput it doesn't scroll properly

**Comment by alvaromb** [comment] 2018-02-19 10:36
Can you set up a repro case in order to be able to solve it? Thanks!

**Comment by N1ghtly** [comment] 2018-02-22 10:46
Just ran into this with KeyboardAwareScrollView too.

**Comment by omar-salah-elboredy** [comment] 2018-03-09 14:55
Reproduction case:
```
<KeyboardAwareFlatList
          data={optionsList}
          renderItem={this._renderItem.bind(this)}
          keyExtractor={this._keyExtractor}
          showsVerticalScrollIndicator={false}
        />
```
And in _renderItem function there is an item that renders a text field **(TextInput)** as following: 
```
 <TextInput
            {...this.props}
            multiline={true} />
```
When the multiline prop is set to _false_ it works fine and scrolls up to text field as intended, but when it is set to _true_ , it fails to scroll up/center the text field as in last case.

Solution/Workaround: I added
 > extraHeight 
prop like this extraHeight={texInputHeight} for now.
I will add screenshots and close the issue as it seems to be solved for me.

**Comment by alvaromb** [comment] 2018-04-06 08:02
Ugh, yes, this has been an ongoing issue since first versions. I will try to get a solution as soon as I can.

**Comment by WaldoJeffers** [comment] 2018-04-16 12:53
I can confirm this is an issue. The workaround is nice, thanks @omar-salah-elboredy . Sadly, it adds an empty block which has a height of `extraHeight` *below* the scrollView, which can not be reaached :/

**Comment by ngocnguyen09910060** [comment] 2018-04-28 17:48
I have same issue with @WaldoJeffers . Please help.

**Comment by bugs181** [comment] 2018-05-07 07:00
One solution is #250. `componentDidUpdate()` fires an `.update()` event and this repositions the `TextInput` directly above the keyboard.

    update = () => {
      const currentlyFocusedField = TextInput.State.currentlyFocusedField()
      const responder = this.getScrollResponder()

      if (!currentlyFocusedField || !responder) {
        return
      }

      this._scrollToFocusedInputWithNodeHandle(
        currentlyFocusedField
      )
    }

**Comment by bugs181** [comment] 2018-05-09 04:57
Update: There's now a PR waiting for review that fixes this issue among others (ideally any time the `TextInput` goes behind the keyboard. Please check out #251

**Comment by mnsrv** [comment] 2018-07-16 16:21
On RN 0.56 #251 didn't work

**Comment by shx1545** [comment] 2018-07-27 08:05
[KeyboardAwareFlatList] 
At the bottom, the TextInput gets the focus and it can be achieved at the top. But when the keyboard shrinks, it doesn't restore its original position
![Uploading image.png…]()

**Comment by omar-salah-elboredy** [comment] 2018-08-09 09:56
@bugs181 Any updates Levi ? 😄

**Comment by bryantee** [comment] 2018-08-31 23:28
@kylethielk This worked for me, but I had to call without `props`

```js
this.scroll.scrollToFocusedInput(...);
```

**Comment by nolan12345** [comment] 2018-09-04 04:56
import { findNodeHandle  } from 'react-native';
  <KeyboardAwareScrollView style={{flex: 1}}
                                                 innerRef={ref => {
                                                     this.scroll = ref;
                                                 }}>

                            <TextInput
                                multiline={true}

                                onFocus={(event: any) => {
                                    this.scroll.props.scrollToFocusedInput(findNodeHandle(event.target))
                                }}/>

                        </KeyboardAwareScrollView>

**Comment by Bobozee** [comment] 2018-10-01 09:56
> Just encountered this issue on RN 0.56. For anyone finding this I was able to workaround this by hacking it together like so:
> 
> ```js
> render() {
>   <KeyboardAwareScrollView  
>         innerRef={ref => {
>           this.scroll = ref;
>         }} />
>             <TextInput 
>                   multiline={true} 
>                   onFocus={(event: any) => {
>                         this.scroll.props.scrollToFocusedInput(ReactNative.findNodeHandle(event.target));
>                   }} />
> </KeyboardAwareScrollView>
> }
> ```



> Just encountered this issue on RN 0.56. For anyone finding this I was able to workaround this by hacking it together like so:
> 
> ```js
> render() {
>   <KeyboardAwareScrollView  
>         innerRef={ref => {
>           this.scroll = ref;
>         }} />
>             <TextInput 
>                   multiline={true} 
>                   onFocus={(event: any) => {
>                         this.scroll.props.scrollToFocusedInput(ReactNative.findNodeHandle(event.target));
>                   }} />
> </KeyboardAwareScrollView>
> }
> ```

onFocus gets not fired when the multiline TextInput changes its height because of user input

**Comment by kumar-raakesh** [comment] 2019-02-28 11:51
<KeyboardAwareScrollView
enableOnAndroid={true}
            extraHeight={100}
            enableAutomaticScroll={true}
            extraScrollHeight={100}
>
  <View>
    <TextInput />
  </View>
</KeyboardAwareScrollView>

**Comment by sanddy-man** [comment] 2019-02-28 12:48
@mitevdev I found the solution.

```
render() {
  <KeyboardAwareScrollView  
        innerRef={ref => {
          this.scroll = ref;
        }} />
            <TextInput 
                  multiline={true} 
                  onContentSizeChange={(event) => {
                        this.scroll.props.scrollToEnd();
                  }} />
</KeyboardAwareScrollView>
}
```

**Comment by devpascoe** [comment] 2019-03-28 05:25
hmmm how do we reference a ref to scrollview if TextInput lives within a component instead of nicely inline.

**Comment by RyanTG** [comment] 2019-06-23 06:32
So strange: it works as expected on _one_ of my multiline TextInputs, but not on another. I know I'm not adding anything to the discussion. But it has me baffled.

**Comment by BatDroid** [comment] 2019-07-01 12:49
the `scrollToFocusedInput` takes a second parameter which is `extraHeight` but it doesn't work seems whatever you pass to it, it will be overwritten in a `update` method with the default `extraHeight` or props.

**Comment by TreeMan360** [comment] 2019-10-26 11:08
Hey guys,

Just incase this helps anyone I solved this nicely using hooks in the following way:
 
1. I wrap all of my screens in a ```Layout ``` component (I use ```React Navigation```).
2. If that Layout contains inputs then I pass ```avoidKeyboard``` into that component. If the layout also scrolls then I pass ```scrollEnabled```.
3. I use ```react-native-keyboard-aware-scroll-view``` wrapped in a component called ```KeyboardAvoidingScrollView```. This uses the React context API to provide access to the ``ref``.
4. I have a ```KeyboardAwareInput``` component which accesses the ``ref`` via the context. If the ref exists then I ```scrollToFocusedInput``` in the ```onContentSizeChange``` handler along with ```findNodeHandle```.

This is working perfectly for me. Here is the code:

**Layout.tsx**
```
import React from 'react'
import { View } from 'react-native'
import { makeStyles } from '../styles/makeStyles'
import { KeyboardAvoidingScrollView } from './KeyboardAvoidingScrollView'

interface IProps {
  avoidKeyboard?: boolean
  scrollEnabled?: boolean
}

export const Layout: React.FunctionComponent<IProps> = ({
  avoidKeyboard = false,
  scrollEnabled = false,
  children,
}) => {
  const Container = <View style={styles.container}>{children}</View>

  return avoidKeyboard ? (
    <KeyboardAvoidingScrollView scrollEnabled={scrollEnabled}>
      {Container}
    </KeyboardAvoidingScrollView>
  ) : (
    Container
  )
}

const styles = makeStyles(theme => ({
  container: {
    ...theme.LayoutContainer.containerStyle,
  },
}))
```

**KeyboardAvoidingScrollView.tsx**
```
import React, { createContext, useContext, useRef } from 'react'
import {
  KeyboardAwareScrollView,
  KeyboardAwareScrollViewProps,
} from 'react-native-keyboard-aware-scroll-view'
import layout from '../constants/Layout'

interface IContext {
  scrollViewRef: React.MutableRefObject<KeyboardAwareScrollView>
}

const KeyboardAvoidingScrollViewContext = createContext<IContext>({
  scrollViewRef: null,
})

export const useKeyboardAvoidingScrollView = () => {
  return useContext(KeyboardAvoidingScrollViewContext)
}

interface IProps extends KeyboardAwareScrollViewProps {
  scrollEnabled?: boolean
}

export const KeyboardAvoidingScrollView: React.FunctionComponent<IProps> = ({
  scrollEnabled = false,
  children,
  ...scrollViewProps
}) => {
  const scrollViewRef = useRef(null)

  return (
    <KeyboardAwareScrollView
      ref={scrollViewRef}
      resetScrollToCoords={{ x: 0, y: 0 }}
      contentContainerStyle={{ flex: 1 }}
      scrollEnabled={scrollEnabled}
      extraHeight={layout.window.height / 4}
      {...scrollViewProps}
    >
      <KeyboardAvoidingScrollViewContext.Provider value={{ scrollViewRef }}>
        {children}
      </KeyboardAvoidingScrollViewContext.Provider>
    </KeyboardAwareScrollView>
  )
}
```

**KeyboardAwareInput.tsx**
```
import React from 'react'
import { findNodeHandle } from 'react-native'
import { Input, InputProps } from 'react-native-elements'
import { useKeyboardAvoidingScrollView } from '../components/KeyboardAvoidingScrollView'

export const KeyboardAwareInput: React.FunctionComponent<
  InputProps
> = inputProps => {
  const { scrollViewRef } = useKeyboardAvoidingScrollView()

  return (
    <Input
      {...inputProps}
      onContentSizeChange={event => {
        if (scrollViewRef && scrollViewRef.current) {
          scrollViewRef.current.scrollToFocusedInput(
            findNodeHandle(event.target)
          )
        }
      }}
    />
  )
}
```

And then an actual usage example: 

**ArrangeInPersonMeeting.tsx** 
_FYI: This is referenced from a ```TabNavigator```,  and in this case inside a ```Modal``` route_

```
import React from 'react'
import { NavigationStackScreenComponent } from 'react-navigation-stack'
import { Layout } from '../../../components/Layout'
import { ModalBottomButton } from '../../../components/ModalBottomButton'
import { IMember } from '../../company/interfaces'
import { EnterLocationDetails } from './EnterLocationDetails'
import { ProposedTimes } from './ProposedTimes'

export const ArrangeInPersonMeeting: NavigationStackScreenComponent = ({
  navigation,
}) => {
  const member: IMember = navigation.dangerouslyGetParent().getParam('member')
  return (
    <Layout avoidKeyboard>
      <ProposedTimes withMember={member} />
      <EnterLocationDetails />
      <ModalBottomButton
        title="Arrange Meeting"
        icon={{ type: 'material-community', name: 'calendar-check' }}
      />
    </Layout>
  )
}
```

**EnterLocationDetails.tsx**
```
import React, { useState } from 'react'
import { View } from 'react-native'
import { CheckBox } from 'react-native-elements'
import { HeaderBar } from '../../../components/HeaderBar'
import { KeyboardAwareInput } from '../../../components/KeyboardAwareInput'
import { Paper } from '../../../components/Paper'

export const EnterLocationDetails: React.FunctionComponent = () => {
  const [meetAtOffice, setMeetAtOffice] = useState(false)
  const [postalCode, setPostalCode] = useState<string>()
  const [details, setDetails] = useState<string>()

  return (
    <View style={{ flex: 1 }}>
      <HeaderBar label="Location" />
      <Paper>
        <View
          style={{
            flexDirection: 'row',
            alignItems: 'center',
          }}
        >
          <KeyboardAwareInput
            placeholder="Enter Postal Code"
            onChangeText={setPostalCode}
            value={postalCode}
            numberOfLines={1}
            maxLength={20}
            containerStyle={{
              flex: 0.5,
            }}
          />
          <CheckBox
            title="Meet at your office"
            checked={meetAtOffice}
            onPress={() => setMeetAtOffice(!meetAtOffice)}
            containerStyle={{
              flex: 0.5,
            }}
          />
        </View>
        <View>
          <KeyboardAwareInput
            placeholder="Please specify any additional place details or directions..."
            onChangeText={setDetails}
            value={details}
            maxLength={500}
            textAlignVertical="top"
            numberOfLines={3}
            multiline
          />
        </View>
      </Paper>
    </View>
  )
}
```

I hope that helps someone resolve this issue in a clean fashion.

Happy coding!

**Comment by ajaykumar97** [comment] 2019-11-16 14:21
> onContentSizeChange={(event) => {
>                         this.scroll.props.scrollToEnd();
>                   }}

I am able to fix this issue as suggested by @sanddy-man but with little change. Instead of using `` this.scroll.props.scrollToEnd();``, I used `` this.scrollRef.props.scrollToFocusedInput(findNodeHandle(event.target));`` as below:

```
render() {
  <KeyboardAwareScrollView  
        innerRef={ref => {
          this.scroll = ref;
        }}
  />
            <TextInput 
                  multiline={true} 
                  onContentSizeChange={(event) => {
                       this.scrollRef.props.scrollToFocusedInput(findNodeHandle(event.target));
                  }}
             />
   </KeyboardAwareScrollView>
}
```

**Comment by Yassir4** [comment] 2020-01-06 13:42
Thank you @ajaykumar97  this is exactly what I was looking for 👍

**Comment by rborn** [comment] 2020-07-15 11:06
I'll close this for being very old. Thanks for all the comments 😻 
A solution seems to be here: https://github.com/APSL/react-native-keyboard-aware-scroll-view/issues/227#issuecomment-554641817

**Closed by rborn** 2020-07-15 11:06 UTC
Labels: enhancement, help wanted

**Comment by kokopelli314** [comment] 2020-07-24 14:54
The solution in [the comment above](https://github.com/APSL/react-native-keyboard-aware-scroll-view/issues/227#issuecomment-554641817) does not work for functional components. While [one solution was provided](https://github.com/APSL/react-native-keyboard-aware-scroll-view/issues/227#issuecomment-546593084) using hooks, it is quite involved and is not an easy fix.

Could we keep this issue open, since the expected behavior of the `KeyboardAwareScrollView` component is to scroll to selected inputs, whether multiline or not? If the current behavior is intended (only scrolling to non-multiline inputs), I suggest the documentation should be updated to make this clear, as it could be a stumbling block for many developers.

**Comment by MorganTrudeau** [comment] 2020-09-25 10:20
Try setting `scrollEnabled={false}` on TextInput. Allows keyboard-scroll-view take over it seems :)

**Comment by alelaru** [comment] 2022-08-31 09:00
I had the same problem and solved with Morgan's solution, so the problem still exists with version 0.9.5

**Comment by GodVampire** [comment] 2022-09-14 01:27
same problem with version 0.9.5

**Comment by laurenzcodes** [comment] 2022-10-14 08:41
Since nothing directly suggested here worked for me, I hacked it to work using different bits from this issue and came to this working solution:

1. Create a ref for the kb-aware scroll view and reference it in the component
`const keyboardScrollViewRef = React.useRef<KeyboardAwareScrollView>(null);`

2. Create a function to handle the contentHeightChange of the input
```ts
  const handleMessageContentSizeChange = (e: React.Component) => {
    if (keyboardScrollViewRef.current) {
      keyboardScrollViewRef.current.scrollToFocusedInput(findNodeHandle(e) || {});
    }
  };
```
3. Call the function in the onContentSizeChange prop of your `TextInput`
```ts
onContentSizeChange={(e: { target: React.Component }) =>
  handleMessageContentSizeChange(e.target)
}
```

I hope this helps somebody else who is struggling with this issue.
