### ISSUE TITLE
IOS - React Native 0.56  -  scrolls to the top

### ISSUE THREAD

**Issue by pinkladywithcoco** [APSL/react-native-keyboard-aware-scroll-view#287] opened 2018-07-30 18:46 UTC
This happens only when the **KeyboardAwareScrollView** contains many elements more or twice the screen height. if you tap on the last element and when the keyboard hides it scrolls to the top...

Please see the gif down below to understand:

![explain](https://user-images.githubusercontent.com/17241724/43417595-afbaee38-943b-11e8-8fcc-7a6ec380e86d.gif)

**Comment by MonFig** [comment] 2018-08-06 18:05
`enableResetScrollToCoords={false}` might help the problem, while there are still issues with InputTexts which at the bottom of the View.

**Comment by hadimostafapour** [comment] 2018-08-16 13:14
@MonFig @pinkladywithcoco This bug caused by RN 0.56
Check this commit: https://github.com/facebook/react-native/pull/19834/commits

**Comment by alvaromb** [comment] 2018-08-22 14:41
Seems an upstream issue, should be resolved with the July version of RN.

**Closed by alvaromb** 2018-08-22 14:41 UTC
Labels: Upstream issue

**Comment by sorakrisc** [comment] 2021-06-30 07:35
> `enableResetScrollToCoords={false}` might help the problem, while there are still issues with InputTexts which at the bottom of the View.

this just help solve the issue but created another issue

setting enableResetScrollToCoords={false} won't remove the padding created by KeyboardAwareScrollView when the keyboard is hidden unless the user scroll
