### ISSUE TITLE
ScrollView is no longer keyboard aware after typing in TextInput

### ISSUE THREAD

**Issue by eli0shin** [APSL/react-native-keyboard-aware-scroll-view#204] opened 2017-12-11 20:43 UTC
On IOS when a TextInput is focused, the component behaves as expected. However, once text is typed in the TextInput, especially when trying to scroll down to let's say a send button, the ScrollView is no longer Keyboard Aware.

I am currently setting `behavior="position"`, and `alwaysBounceVertical={false}` as a work around, but would like to see this functionality working without requiring the use of those props

**Comment by NichAga** [comment] 2017-12-13 15:55
It happens to me too.

**Comment by holleB** [comment] 2017-12-14 15:57
Could be a duplicate of #186 . If you mean what I think you mean it's possible that there is a bug in `componentWillReceiveProps` of `KeyboardAwareHOC.js`. Every time you type text in the TextInput the method gets called and keyboardSpace get's set to `0` (if it's not in a tabbar). So keyboard layout height gets ignored even if the keyboard is visible.

@alvaromb in old versions (mixin based) this code was in `setViewIsInsideTabBar` in `KeyboardAwareMixin.js`. And that was called in `componentWillMount` of the components. Shouldn't it in a similar place in in the HOC?

**Comment by LRNZ09** [comment] 2018-01-12 14:10
I can also confirm this, but I don't know where do @eli0shin put the prop `behavior` since ScrollView does not have it.

**Comment by alvaromb** [comment] 2018-01-12 14:47
Can you test the new release? https://github.com/APSL/react-native-keyboard-aware-scroll-view/releases/tag/v0.4.2

Ping me if this issue still persists and I'll reopen.

Thanks.

**Closed by alvaromb** 2018-01-12 14:47 UTC

**Comment by ChrisLahaye** [comment] 2018-01-13 01:20
@alvaromb wanted to confirm that with 0.4.2 the issue is fixed. Awaiting the release at npmjs. Thank you for your work!

**Comment by alvaromb** [comment] 2018-01-15 08:55
Sorry, I forgot to release it!

Done, thanks for the heads up @ChrisLahaye!!
