### ISSUE TITLE
scrollview bounces when textinput focused

### ISSUE THREAD

**Issue by RSSfeed** [APSL/react-native-keyboard-aware-scroll-view#217] opened 2018-01-26 10:32 UTC
![keyboardawaremove mp4](https://user-images.githubusercontent.com/4246696/35435754-2ba91df4-028c-11e8-8eba-d43119c8c495.gif)

Code:

    <KeyboardAwareScrollView
        style={{backgroundColor: '#f7f7f7'}}
        enableResetScrollToCoords={false}
        keyboardOpeningTime={300}
    >{/* ... */}</KeyboardAwareScrollView>

Needed to add `enableResetScrollToCoords`, otherwise the ScrollView would have been scrolled to top when Keyboard was dismissed interactively. Also added an higher `keyboardOpeningTime`, so it scrolls smoother when ScrollView actually needs to be pushed upwards.

As seen in gif above, there is no need for scrollview to be adjusted. How may I prevent this behavior?

**Comment by MyGuySi** [comment] 2018-02-06 12:37
Any ETA on a fix for this? Just run into a similar issue which is probably related.

When switching focus from one input to another it bounces first

![feb-06-2018 12-36-06](https://user-images.githubusercontent.com/12952977/35860072-77abb7fa-0b3a-11e8-9689-9d69856aaa69.gif)

**Comment by mattychen** [comment] 2018-07-26 21:55
@RSSfeed  I was able to get around this by removing the React Navigation Header on ios. Does that potentially work for you?

**Comment by luco** [comment] 2018-07-27 13:15
Still having this issue.

**Comment by femiveys** [comment] 2018-07-30 12:52
I have the same issue.

**Comment by avivajohnson** [comment] 2018-08-10 19:51
I was having similar issues with the scrollview bouncing when focusing on a TextInput, and changing 

```<KeyboardAwareScrollView style={styles.scroll}>```
to
```<KeyboardAwareScrollView contentContainerStyle={styles.scroll}>```

seemed to fix it for me.

**Comment by alvaromb** [comment] 2018-08-22 15:07
A temporary workaround is to remove `keyboardOpeningTime`.

**Comment by alvaromb** [comment] 2018-08-22 15:15
I'll be working on this issue this week, thanks for reporting.

**Comment by sapjax** [comment] 2018-09-09 06:55
same issue in 0.7.2.

**Comment by sapjax** [comment] 2018-09-09 10:48
@alvaromb  I found this issue is caused by react-navigation,  I add `extraHeight={-64}` then it works.

**Comment by kalraneeraj24550** [comment] 2018-11-02 08:01
how to resolve this issue plz help

**Comment by sapjax** [comment] 2018-12-05 11:01
@KryDos  yes, it is.

**Closed** 2018-12-10 14:30 UTC

**Comment by Return-1** [comment] 2019-02-08 11:39
Is the negative extraHeight solution the proposed one for this? I can confirm ( as per #340) that this issue still remains

**Comment by williamgrosset** [comment] 2019-07-05 06:59
I'm using this library + react-navigation and setting `extraHeight={90}` with a `<TextInput />` at the footer of the screen seemed to work for me (smooth scrolling with no jumps)

**Comment by arled** [comment] 2019-09-09 13:22
The same happens with `KeyboardAvoidingView` but above solution do not work.

**Comment by iway1** [comment] 2022-05-20 20:02
Still broken in 2022. One workaround is to set `multiline={true}` and `blurOnSubmit={true}`. 

If you want to try the negative extra height solution, use the `useHeaderHeight` hook from `@react-navigation/native`, since it always has the correct header height.

Also note that the `extraHeight` solution will cause the library to no longer work with multiline inputs.

No idea how something like this gets marked as closed tbh it's a bug that's never been fixed

**Comment by rcfrias** [comment] 2022-08-09 00:10
As @alvaromb mentioned, the final solution to this is:
`keyboardOpeningTime={0}`
