### ISSUE TITLE
Not working on 0.29 :(

### ISSUE THREAD

**Issue by nicoecheza** [APSL/react-native-keyboard-aware-scroll-view#48] opened 2016-07-18 19:46 UTC

**Comment by tomauty** [comment] 2016-07-19 15:13
Do you get this as well?

![simulator screen shot jul 19 2016 11 13 15 am](https://cloud.githubusercontent.com/assets/1112872/16955201/cfeef240-4da1-11e6-9989-1d0d89557ced.png)

**Comment by alvaromb** [comment] 2016-07-19 15:14
Oops, will test under 0.29 tomorrow!

Thanks for the report.

**Comment by nicoecheza** [comment] 2016-07-19 15:14
Nope, but I'm in Android, didn't check on iOS

**Comment by tomauty** [comment] 2016-07-19 15:25
My issue was actually caused by passing the `event` as the first argument of `scrollToFocusedInput`, rather than the node.

**Comment by JosephDev** [comment] 2016-07-19 15:52
I have no problem with RN 0.29.0 on both of iOS and Android
Here is my package information
"react": "^15.2.0",
"react-native": "^0.29.0",

**Comment by alvaromb** [comment] 2016-07-20 06:24
Ok!

Closing the issue. Feel free to ping me if this pops up again.

**Closed by alvaromb** 2016-07-20 06:24 UTC

**Comment by niranjan-b-prajapati** [comment] 2016-10-19 12:17
I am getting the same issue.

Following is the log :

2016-10-19 17:41:48.403 [error][tid:com.facebook.react.ShadowQueue][RCTConvert.m:59] JSON value '{
    "_dispatchInstances" = "<null>";
    "_dispatchListeners" = "<null>";
    "_targetInst" = "<null>";
    bubbles = "<null>";
    cancelable = "<null>";
    currentTarget =     {
    };
    defaultPrevented = "<null>";
    destructor =     {
    };
    dispatchConfig = "<null>";
    eventPhase = "<null>";
    isDefaultPrevented = "<null>";
    isPersistent =     {
    };
    isPropagationStopped = "<null>";
    isTrusted = "<null>";
    nativeEvent = "<null>";
    persist =     {
    };
    preventDefault =     {
        thatReturns =         {
        };
        thatReturnsArgument =         {
        };
        thatReturnsFalse =         {
        };
        thatReturnsNull =         {
        };
        thatReturnsThis =         {
        };
        thatReturnsTrue =         {
        };
    };
    stopPropagation =     {
        thatReturns =         {
        };
        thatReturnsArgument =         {
        };
        thatReturnsFalse =         {
        };
        thatReturnsNull =         {
        };
        thatReturnsThis =         {
        };
        thatReturnsTrue =         {
        };
    };
    target = "<null>";
    timeStamp =     {
    };
    type = "<null>";
}' of type NSMutableDictionary cannot be converted to NSNumber
2016-10-19 17:41:48.404 [error][tid:com.facebook.react.ShadowQueue][RCTModuleMethod.m:57] Argument 0 ({
    "_dispatchInstances" = "<null>";
    "_dispatchListeners" = "<null>";
    "_targetInst" = "<null>";
    bubbles = "<null>";
    cancelable = "<null>";
    currentTarget =     {
    };
    defaultPrevented = "<null>";
    destructor =     {
    };
    dispatchConfig = "<null>";
    eventPhase = "<null>";
    isDefaultPrevented = "<null>";
    isPersistent =     {
    };
    isPropagationStopped = "<null>";
    isTrusted = "<null>";
    nativeEvent = "<null>";
    persist =     {
    };
    preventDefault =     {
        thatReturns =         {
        };
        thatReturnsArgument =         {
        };
        thatReturnsFalse =         {
        };
        thatReturnsNull =         {
        };
        thatReturnsThis =         {
        };
        thatReturnsTrue =         {
        };
    };
    stopPropagation =     {
        thatReturns =         {
        };
        thatReturnsArgument =         {
        };
        thatReturnsFalse =         {
        };
        thatReturnsNull =         {
        };
        thatReturnsThis =         {
        };
        thatReturnsTrue =         {
        };
    };
    target = "<null>";
    timeStamp =     {
    };
    type = "<null>";
}) of RCTUIManager. could not be processed. Aborting method call.

Following is my function :
```
_scrollToInput(event, refName) {
    let node = ReactNative.findNodeHandle(this.refs[refName]);
    let extraHeight = refName === "city" || refName === "locality" || refName === "zipCode" ? 140 : 50;
   this.refs.scroll.scrollToFocusedInput(event, node, extraHeight);
  }
```
Following is my implementation:

```
<KeyboardAwareScrollView showsVerticalScrollIndicator={false} ref="scroll" style={styles.scrollContainer}>
<Collapsible collapsed={!this.state.teacherChecked}>
                  <MKTextField
                    autoCorrect={false}
                    maxLength={40}
                    value={this.state.address1}
                    ref='address1'
                    onFocus={(event) => { this._scrollToInput(event, 'address1') } }
                    onSubmitEditing={dismissKeyboard}
                    placeholder = "Address Line 1"
                    onChangeText={this.onAddress1Change.bind(this) }
                    tintColor='#999999'
                    highlightColor='#B80012'
                    floatingLabelEnabled={true}
                    style={styles.textField}/>
                  <MKTextField
                    autoCorrect={false}
                    onSubmitEditing={dismissKeyboard}
                    maxLength={40}
                    value={this.state.address2}
                    ref='address2'
                    onFocus={(event) => { this._scrollToInput(event, 'address2') } }
                    placeholder = "Address Line 2"
                    onChangeText={this.onAddress2Change.bind(this) }
                    tintColor='#999999'
                    highlightColor='#B80012'
                    floatingLabelEnabled={true}
                    style={styles.textField}/>

                  <MKTextField
                    maxLength={60}
                    blurOnSubmit={false}
                    autoCorrect={false}
                    value={this.state.city}
                    ref='city'
                    onFocus={(event) => { this._scrollToInput(event, 'city') } }
                    onSubmitEditing={dismissKeyboard}
                    placeholder = "City"
                    onChangeText={this.onCityChange.bind(this) }
                    tintColor='#999999'
                    highlightColor='#B80012'
                    floatingLabelEnabled={true}
                    style={styles.textField}/>

                  <ListView
                    style={ citiesData.length > 4 ? { height: 160 } : {}}
                    keyboardShouldPersistTaps={true}
                    dataSource={ds.cloneWithRows(citiesData.length === 1 && comp(this.state.city, citiesData[0]) ? [] : citiesData) }
                    renderRow={this.renderItem.bind(this) } />


                  <MKTextField
                    maxLength={60}
                    //blurOnSubmit={false}
                    autoCorrect={false}
                    value={this.state.locality}
                    ref='locality'
                    onFocus={(event) => { this._scrollToInput(event, 'locality') } }
                    onSubmitEditing={dismissKeyboard}
                    placeholder = "Locality"
                    onChangeText={this.onLocalityChange.bind(this) }
                    tintColor='#999999'
                    highlightColor='#B80012'
                    floatingLabelEnabled={true}
                    style={styles.textField}/>

                  <ListView
                    style={ localitiesData.length > 4 ? { height: 160 } : {}}
                    keyboardShouldPersistTaps={true}
                    dataSource={ds.cloneWithRows(localitiesData.length === 1 && comp(this.state.locality, localitiesData[0]) ? [] : localitiesData) }
                    renderRow={this.renderLocalityItem.bind(this, this.props.localitiesAndZipCodes) } />

                  <MKTextField
                    blurOnSubmit={false}
                    onSubmitEditing={dismissKeyboard}
                    maxLength={6}
                    value={this.state.zipCode}
                    ref='zipCode'
                    onFocus={(event) => { this._scrollToInput(event, 'zipCode') } }
                    placeholder = "ZIP Code"
                    keyboardType = 'numeric'
                    onChangeText={this.onZipCodeChange.bind(this) }
                    tintColor='#999999'
                    highlightColor='#B80012'
                    floatingLabelEnabled={true}
                    style={styles.textField}/>
                  <ListView
                    style={ zipCodesData.length > 4 ? { height: 160 } : {}}
                    keyboardShouldPersistTaps={true}
                    dataSource={ds.cloneWithRows(zipCodesData.length === 1 && comp(this.state.zipCode, zipCodesData[0]) ? [] : zipCodesData) }
                    renderRow={this.renderZipCodeItem.bind(this, this.props.localitiesAndZipCodes) } />

                  <MKTextField
                    onSubmitEditing={dismissKeyboard}
                    maxLength={40}
                    value={this.state.landmark}
                    ref='landmark'
                    onFocus={(event) => { this._scrollToInput(event, 'landmark') } }
                    placeholder = "Landmark"
                    onChangeText={this.onLandmarkChange.bind(this) }
                    tintColor='#999999'
                    highlightColor='#B80012'
                    floatingLabelEnabled={true}
                    style={styles.textField}/>
                </Collapsible>
</KeyboardAwareScrollView>
```

I think the error is created due to 
`this.refs.scroll.scrollToFocusedInput(event, node, extraHeight);`
as when i comment the above mentioned line the error never comes.

Following are my package.json values:
```
"react": "^15.3.1",
"react-native": "^0.34.1",
"react-native-keyboard-aware-scroll-view": "^0.2.1",
```

Please let me know if i am doing something wrong in the code.
